name: Build-All-Platforms

on:
  push:
    branches: ["main"]

  workflow_dispatch:

jobs:

  build:
    strategy:
      matrix:
        os: [macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.7'
          architecture: 'x64'

      - name: Install Dependencies
        run: |
          pip install -r app/requirements.txt

      - name: Build Executable
        uses: Nuitka/Nuitka-Action@main
        with:
          nuitka-version: main
          script-name: app/MotionFrame.py
          onefile: true
          enable-plugins: pyside6

      - uses: skymatic/code-sign-action@v3.0.0
        with:
          certificate: '${{ secrets.CERTIFICATE }}'
          password: '${{ secrets.PASSWORD }}'
          certificatesha1: '${{ secrets.CERTHASH }}'
          certificatename: '${{ secrets.CERTNAME }}'
          description: 'MotionFrame'
          timestampUrl: 'http://timestamp.digicert.com'
          folder: 'build'
          recursive: true

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ runner.os }} Build
          path: |
            build/*.exe
            build/*.app/**/*
          include-hidden-files: true
